### ISSUE TITLE
Misc | Resetting Paste example link does not reset the bound input fields

### ISSUE THREAD

**Issue by pushpendraKh** [AdvancedThreatAnalytics/threat-analytics-search#45]
### Description

When resetting link from "Paste Example Link" does not reset the binding input fields like `Host (IP Address/Hostname)`, `Port number`, `Collection Name`

### How to reproduce
- Go to NetWitness TAB
- Paste any valid link on "Paste example link from NetWitness Investigator to autofill settings" and hit enter ( https://www.netwitness.com:80?collection=89 )
-  Form above step `Host` `Port number` etc (all bound fields) gets filled
- Now erase/reset the link
- Note that it does not reset the bound fields (like `Host`, `Port Number`), etc

**Comment by jfmdev** [comment]
That's not a bug: it's a feature  😆 

* Go to NetWitness TAB
 * Paste any valid link on "Paste example link from NetWitness Investigator to autofill settings" and hit enter ( https://www.netwitness.com:80?collection=89 )
 * Form above step Host Port number etc (all bound fields) gets filled
 * Modify the port, because after copying the link the port was modified.
 * Now erase/reset the link because it don't longer reflects the current configuration.
 * All your changes get erased  🤯
